In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("../data/ssd_data.csv")
df.head()

,temperature,wear_level,power_on_hours,write_cycles,ECC_error_rate,bad_blocks,RUL,health_status
0,50.0,3.2,15633,97789,0.0168,1,9408,Healthy
1,43.6,46.9,44233,20058,0.0232,2,5725,Warning
2,51.5,92.5,44967,82807,0.0012,3,1858,Critical
3,60.2,39.8,1416,31604,0.0162,1,6506,Healthy
4,42.7,62.5,38072,99102,0.0113,1,4783,Warning


In [2]:
FEATURES = [
    "temperature",
    "wear_level",
    "power_on_hours",
    "write_cycles",
    "ECC_error_rate",
    "bad_blocks"
]

X = df[FEATURES]

In [3]:
y_class = df["health_status"]
y_rul = df["RUL"]


In [4]:
# Manual human-friendly encoding
mapping = {
    "Healthy": 0,
    "Warning": 1,
    "Critical": 2
}

y_class_enc = y_class.map(mapping)

print(mapping)

{'Healthy': 0, 'Warning': 1, 'Critical': 2}


In [5]:
from sklearn.model_selection import train_test_split

X_train, X_test, yc_train, yc_test, yr_train, yr_test = train_test_split(
    X,
    y_class_enc,
    y_rul,
    test_size=0.2,
    random_state=42,
    stratify=y_class_enc
)

In [6]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_s = scaler.fit_transform(X_train)

X_test_s = scaler.transform(X_test)

In [7]:
print(X_train_s.shape)
print(X_test_s.shape)

(6400, 6)
(1600, 6)


In [8]:
print(X_train_s[:5])

[[ 0.33013355  0.43988336 -1.62738335  0.48386598 -0.68732672 -0.71811592]
 [-1.68087984 -0.17993509  1.09294769  1.70245271  0.31974769 -0.0207044 ]
 [-1.55081429  1.22937278  0.34373492  0.56578691 -0.91279115  0.67670711]
 [-1.03055212  0.0763027   0.3163264  -0.76792447  0.72558365  1.37411863]
 [-0.07006812  0.87964281  1.49266696  0.26056149  0.54020179 -1.41552744]]


In [9]:
import numpy as np

print(np.mean(X_train_s, axis=0))

[ 5.65658631e-16  2.43971510e-16  8.09075029e-17  1.26010313e-16
 -8.88178420e-17 -6.88338275e-17]


In [10]:
print(np.std(X_train_s, axis=0))

[1. 1. 1. 1. 1. 1.]


In [11]:
import joblib

joblib.dump(scaler, "../models/scaler.pkl")

['../models/scaler.pkl']

In [12]:
joblib.dump(mapping, "../models/label_mapping.pkl")

['../models/label_mapping.pkl']

In [13]:
import numpy as np

np.save("../data/X_train.npy", X_train_s)
np.save("../data/X_test.npy", X_test_s)

np.save("../data/yc_train.npy", yc_train)
np.save("../data/yc_test.npy", yc_test)

np.save("../data/yr_train.npy", yr_train)
np.save("../data/yr_test.npy", yr_test)

In [14]:
print(X_train_s.shape)
print(X_test_s.shape)
print(yc_train.shape)
print(yc_test.shape)
print(yr_train.shape)
print(yr_test.shape)

(6400, 6)
(1600, 6)
(6400,)
(1600,)
(6400,)
(1600,)


In [15]:
label_mapping = joblib.load("../models/label_mapping.pkl")

class_names = list(label_mapping.keys())

print(class_names)

['Healthy', 'Warning', 'Critical']


In [1]:
import joblib

mapping = joblib.load("../models/label_mapping.pkl")

print(type(mapping))
print(mapping)

<class 'dict'>
{'Healthy': 0, 'Warning': 1, 'Critical': 2}


In [2]:
import joblib
import numpy as np

scaler = joblib.load("../models/scaler.pkl")
clf = joblib.load("../models/classifier.pkl")

sample = np.array([[62, 85, 35000, 80000, 0.08, 9]])

scaled = scaler.transform(sample)

print(clf.predict(scaled))

[1]


C:\Users\SKANDHAS\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
